namespace EntryNow.WebApp.Constants
{
    public static class Global
    {
		public static readonly string[] Districts = { "Matiari" };
		
		public static readonly string[] Cities = { "Hala New", "Hala Old", "Bhit Shah", "Saeedabad", "Matiari" };

        public static readonly string[] Talukas = { "Hala", "Saeedabad", "Matiari" };

        //public static readonly string[] UnionCounsil_Hala = { "Khandu", "Karam Khan Nizamani", "Ajan Shah", "Bhanoth", "Bhit Shah", "Fateh Muhammad Shah Ajnani" };
        //public static readonly string[] UnionCounsil_Saeedabad = { "Abdul Wahid Burira", "BD Kaka", "Faqeerabad", "Makhdoom joon Landhiyoon", 
        //    "Old Saeedabad", "Ramzan Unar", "Shahmir Rahu", "Sikandarabad", "Zair Peer" };
        //public static readonly string[] UnionCounsil_Matiari = { "" };

//        public static readonly string[] Villages_Khandu = { "Ali Akbar Jo Kot",
//		"Ali Gul Khoso-Malook Sanjrani",
//		"Ali Nawaz Borrabni",
//		"Achi Masjid",
//		"Chandi Bhacho",
//		"Dino Majeedano",
//		"Dodo Roonjhani",
//		"Dhani Bux Char",
//		"Dural Khoso",
//		"Dadu Mirbahar",
//		"Gahee Lakho-Nizamani",
//		"Golo Machi",
//		"Gulab Rahu",
//		"Haji Ghamoo Char",
//		"Haji Siddique Rahu",
//		"Haji Muhammad salih Bhacho-Soof Bhacho",
//		"Jadam Bughio",
//		"Jummo Bhacho",
//		"Jummo Khyber",
//		"Jam Khos",
//		"Khandoo",
//		"Laique Dino",
//		"Lakho Rahu",
//		"Laung Rahu/Usman Rahu",
//		"Lakha Dino Khoso-Abdul Ghafoo Khoso",
//		"Mehyar Machi",
//		"Mithu Rahu",
//		"Mundrani Char",
//		"Manzoor Jo Kot/Babul Kot",
//		"Mir Bozdar",
//		"Nabi Bux Char",
//		"Punhal Jamali",
//		"Qasim Khokhar",
//		"Sain Bux Roonjhani Kasai",
//		"Sher Sangrasi Majeedano",
//		"Shakeel Chandio-Khaskheli",
//		"Salamat Khoso",
//		"Siddique Khoso",
//		"Wali Muhammad Nizamani",
//		"Waryal Mirbahar",
//		"Wada Salaro" };
//		public static readonly string[] Villages_KaramKhanNizamani = { "Allah Bux Nizamani",
//		"Ali Muhammad Nizamani",
//		"Allah Warayo Khaskheli",
//		"Allah Bux Aaphan",
//		"Arab Nizamani",
//		"Badal Nizamani",
//		"Batho Raees Ali Ahmed Khan",
//		"Baqar Khan Nizamani",
//		"Darya Khan Bughio",
//		"Gul Muhammad Nizamani",
//		"Ghulam Hussain Laghari",
//		"Godar khokhar",
//		"Ghulam Hyder Nizamani",
//		"Ghulam Nabi Rind",
//		"Hayat Khan Nizamani",
//		"Jado Gahothi",
//		"Kot Jaffar Sahito",
//		"Khan Muhammad Nizamani",
//		"Kalri",
//		"Karam khan Nizamani",
//		"Mahee Mochi",
//		"Malook Khan Laghari",
//		"Mitho Sahito",
//		"Qaim Raheem Ahmadani",
//		"Qasim Bughio",
//		"Shadi Khokhar",
//		"Sobho Khan Nizamani",
//		"Sultan Sahito",
//		"Wadal Daheri",
//		"Yameen Aaphan" };
//		public static readonly string[] Villages_AjanShah = { "Ajan Shah",
//		"Allah wasayo Lakho",
//		"Amin lakho",
//		"Allah dino Mahar",
//		"Bhadur jarr",
//		"Bharam meer jat",
//		"Chowdagi",
//		"Dodo Meer jat",
//		"Esso Khan naar",
//		"Ghulam haider khaskheli",
//		"Ghulam umrani",
//		"Gahi khan chajro",
//		"Haji khan Bughio",
//		"Hayat lakho",
//		"Hub ali Lakho",
//		"Haboo kolhi",
//		"Jan muhammad sangrasi",
//		"Jogi colony/village",
//		"Kehar lajwani",
//		"Mohammad raheem lakho",
//		"Mahmood Dahri",
//		"Muhammad Sand",
//		"Mohammad khan junejo",
//		"Muhammad Hassan Rind",
//		"Mola bux panhwar",
//		"Noor muhammad Mangrio",
//		"Paryal Lakho",
//		"Peer bux Mahar",
//		"Qaim din Khaskheli",
//		"Rahoond",
//		"Railway Station",
//		"Sain dino pahor",
//		"Sangrasiabad ",
//		"Sher faqeer",
//		"Sher khan malokhani",
//		"Sultan lakho",
//		"Saleh Mangrio",
//		"Shah Muhammad daheri",
//		"Selani faqeer",
//		"Saleem Raho",
//		"Wasi Murad shah",
//		"Yar muhammad khoso" };
//		public static readonly string[] Villages_Bhanoth = { "Ali sher otho",
//		"Allah bux Balal",
//		"Ali Murad Nar",
//		"Aman Abro",
//		"Bhanoth",
//		"Bachal shah ji otaq",
//		"Bago Abro",
//		"Barocho Bag",
//		"Daryah Khan khoso",
//		"Deen Muhammad Balal",
//		"Dhani bux Balal",
//		"Fareed faram",
//		"Gohram Khoso",
//		"Gahoth",
//		"Ghulam Muhammad Balal",
//		"Ghulam Hussain Laghari",
//		"Gul faram",
//		"Hamzo Babur",
//		"Haji soomar keerio",
//		"Jamal khan Daheri",
//		"Jaro Gahothi",
//		"Jan Muhammad Laghari",
//		"Kehar Colony",
//		"Kabil Abro",
//		"Mari Muhammad khan",
//		"Malook Khan Laghari",
//		"Meeran  Pur",
//		"Mevo Balal",
//		"Peero waah",
//		"Pareyo Bhanoth",
//		"Sarang Solangi",
//		"Talo Khan Laghari",
//		"Tariha",
//		"Wali Muhammad Rind",
//		"Walliullah ji otaq",
//		"Wazeer Rind",
//		"Wanjheri",
//		"Yar Muhammad Balal",
//		"Zahid Gahothi" };
//		public static readonly string[] Villages_BhitShah = { "Ahmad khan Thaheem / kevro",
//		"Allah Dino chand",
//		"Allah Dino Shah",
//		"Allah Dino Shah Nar",
//		"Bilawal Shah",
//		"Bachu Paryhiar",
//		"Bahawal Khan khoso",
//		"Behram Mirjat",
//		"Chutto Malookhani",
//		"Dodo Samoon",
//		"Daud Sangrasi",
//		"Eso Daheri",
//		"Fatoo Khyber",
//		"Ghulam Hyder Malookhani",
//		"Gul Khyber",
//		"Ghulam ali Panhwar",
//		"Gul sehto",
//		"Gahanwar Khan Shahani",
//		"Haji Soomar Keerio",
//		"Hasil Lashari",
//		"Hero kolhi",
//		"Illyass Parhiyar",
//		"Karim Rind",
//		"Karnal Hashmi",
//		"Kutub Shahani",
//		"Kamil Sand",
//		"Kot Siddique Thaheem",
//		"Kot Ali Muhammad Rajar",
//		"Khuda Bux Sethar",
//		"Khuda Bux sangrasi",
//		"Lalo Thaheem",
//		"Mula Makhan",
//		"Misri Lashari",
//		"Mahmood Thaheem",
//		"Mahmood Thaheem",
//		"Maakan Wassan At Rajar jo Kot",
//		"Mirzo Khan Shahani",
//		"Muhammmad Ali shahani",
//		"Pathan khoso",
//		"Qaiser Khan Khoso",
//		"Salamat keerio",
//		"Sarang Wasan",
//		"Seddique Brohi",
//		"Shafi Muhammad Parhiyar",
//		"Siddique Thaheem",
//		"Yaqoob Lashari",
//		"Yar Muhammad Rind" };
//		public static readonly string[] Villages_FatehMuhammadShahAjnani = { "Allha Dino jalalni",
//		"Allha Dino Chandio",
//		"Arif Khan Nizamani",
//		"Aarab Khan Nizamani",
//		"Ali Muhammad Laghari",
//		"Arif Nizamani",
//		"Abdul Aleem Chand",
//		"Allha Rakhyo Chandio",
//		"Bachal Rajar",
//		"Budhal Memon",
//		"Dabri",
//		"Digano Laghari",
//		"Dargah Fateh Muhammad Shah",
//		"Ghulam Muhammad Ghambhir",
//		"Gul Muhammad Laghari",
//		"Ghulam Hussain Nizamani",
//		"Haji Hussain Bux Laghari",
//		"Haji Ali Nawaz Daheri",
//		"Hamzo Babur",
//		"Jamal Hajano",
//		"Jan Muhammad Dhib",
//		"Jan Muhammad Laghari",
//		"Jamal Nizamani",
//		"Kot Hamid Shah",
//		"Kabil Sahito",
//		"Kot Ahmed Shah",
//		"Kot sain Shams Din Shah",
//		"Kot umar memon",
//		"Lal Bux Chand",
//		"Maroof Bhambhuro",
//		"Major Chandio",
//		"Malik Bhacho",
//		"Malook Daheri",
//		"Muhammad Moosa Ghambhir",
//		"Mehmood Daheri",
//		"Nawab bhambhuro",
//		"Noor Muhammad Jalalani",
//		"Pooto Gahothe",
//		"Pir Bilawali",
//		"Raheem Mochi",
//		"Sultan Farash",
//		"Saeed Khan Laghari",
//		"Uris Abro",
//		"Ustad Sher Muhammad Laghari / Wari wara Laghari",
//		"Unar Khaskheli",
//		"Wahindari",
//		"Wahinyal Bhanoth",
//		"Wikiyo Machi",
//		"Wachu Bhambhuro",
//		"Wikiyo Bhambhuro" };
//		public static readonly string[] Villages_AbdulWahidBurira = { "Abdul Raheem Hajano",
//		"Abdul Wahid Burira",
//		"Allam Khan Rind",
//		"Allan Hajano",
//		"Bachal Unar",
//		"Bisti Bagh",
//		"Bagoo Hajano",
//		"Baloch Khan Colony",
//		"Dahron Hajano",
//		"Dargha Jamal Shah",
//		"Dodo Khan Hajano",
//		"Faqeer Hussain Bux Khoso",
//		"Gul Muhammad brohi",
//		"Gul Muhammad Khaskheli",
//		"Gulan Hajano",
//		"Haji Siddique",
//		"Haji Achar Hajano",
//		"Haji Essa Khaskheli",
//		"Haji Ramzan Sahito",
//		"Haji Razi Hajano",
//		"Imam Bux Hajano",
//		"Jado Gahoti",
//		"Kamil Laghari",
//		"Kamloo",
//		"Karo Daheri",
//		"Kot Makhdoom Fazal Hussain",
//		"Khuda Bux Hajano",
//		"Meer Colony",
//		"Muhammad Yousif Hajano",
//		"Mansoora",
//		"Mitho Shah",
//		"Muhammad Mured",
//		"Muhammad Yousif Sirae",
//		"Nazeer Hajano",
//		"Palio Hajano",
//		"Qasim Haloo",
//		"Rano Bughio",
//		"Salhar Hajano",
//		"Sabho Kamloo",
//		"Talib Khaskheli",
//		"Tayab Daheri",
//		"Ubhoro Daheri",
//		"Younis Jamali" };
//		public static readonly string[] Villages_BDKaka = { "Ahmed Brohi",
//		"Ali Sher Khaskheli",
//		"Allah Bachayo Kaka",
//		"Amb Kaka",
//		"Abdul Raoof kaka/Roonjha",
//		"Allah Dino Kaka (Book)",
//		"Ameer Bux Jamali",
//		"Bhale dino Kaka",
//		"Begoo Kaka",
//		"Bachal Manginhar",
//		"Bhaly Dino kaka",
//		"Faiz Muhammad Sahito",
//		"Faqeer Muhammad Kaka",
//		"Full Kaka",
//		"Gul Muhammad Kaka",
//		"Ibraheem Hajano",
//		"Ibraheem Chana",
//		"Jaffar Kaka",
//		"Jaffar Hajano",
//		"Khair Muhammad kaka",
//		"Khair Muhammad Brohi",
//		"Khan Muhammad Ujan",
//		"Khuda Bux Kaka",
//		"Kot Ibraheem Kaka",
//		"Laloo khaskheli",
//		"Mian Chutto Kaka",
//		"Molvi Ghulam Hyder Jamali/ Bangladesh",
//		"Muhammad Brohi",
//		"Meer Jat Lashari",
//		"Moledino Hajano",
//		"Muhammad Shareef Ujan",
//		"Mudho kaka",
//		"Noor Muhammad Umrani",
//		"Nabi Bux Jamali",
//		"Nabi Bux Khaskheli",
//		"Ober Soomro",
//		"Pahar Jamali",
//		"Pandhi Hingoro",
//		"Pir Bux Sahito",
//		"Paryo kaka",
//		"Pahar Kaka",
//		"Qazi Gul Hassan Kaka",
//		"Qasim Domki",
//		"Ramzan Khaskheli",
//		"Riaz Ali Rind",
//		"Shaikh Muhammad shah",
//		"Soomer Birahmani",
//		"Seracho Kaka",
//		"Tawakali Domki",
//		"Tooh Hinghoro",
//		"Yousif Jamali" };
//		public static readonly string[] Villages_Faqeerabad = { "Allah Bux Khoso",
//		"Ameen Lakho",
//		"Abdul Ghafoor Sobcho",
//		"Achi Masjid Faqeerabad",
//		"Badar Lakho",
//		"Bachu Rind",
//		"Bhae Khan Sohibcho",
//		"Dado Karim Dino Rahoo",
//		"Darga Pir Jhano",
//		"Dalo Keti",
//		"Faqeerabad",
//		"Gul badin",
//		"Gulsher Abro",
//		"Golo Unar",
//		"Ghulam Muhammad Manahi",
//		"Haji Gulo Rind",
//		"Haji Raheem khan mari",
//		"Hashim abro",
//		"Haji Ali Murad Rahoo Otaq",
//		"Ilyas Abrejo",
//		"Jaffar Machi",
//		"Jumon Barhmani",
//		"Khamiso Machi",
//		"Karo Keti",
//		"Kazi Hanif Sohibcho",
//		"Khamiso Machi",
//		"Khameeso Khan",
//		"Long Khaskheli",
//		"Muhammad Khan Machi",
//		"Muhammad Ali Turk",
//		"Muhammad Ilyas Ghambhir",
//		"Muhammad Khan Machi",
//		"Muhammad Hashim Sohibcho",
//		"Noorabad",
//		"Nabi Bux Chang",
//		"Pathan Rind",
//		"Pinyal Rind",
//		"Pir Jhando",
//		"Shah Muhammad Shah",
//		"Sher Khan Majidano",
//		"Sher Muhammad Rind",
//		"Tulsi Kolhi" };
//		public static readonly string[] Villages_MakhdoomjoonLandhiyoon = { "Aapun Machi Ji Bani",
//		"Ali Dost",
//		"Ali Sher Machi",
//		"Allah Bachayo Machi",
//		"Chandui Machi",
//		"Dare Wara Bugti",
//		"Gul Muhammad Mahar",
//		"Ghafoor Munchi Ji Bani",
//		"Ghulam Machi",
//		"Gul Muhammad Solangi",
//		"Haji Ahmed Laghari",
//		"Haji Muhammad Hassan Keeria",
//		"Hafiz Sanai Boring",
//		"Hurri wara Bugti",
//		"Jumoo Laghari",
//		"Khamiso Solangi",
//		"Khudabad",
//		"Kot Ahmed Shah",
//		"Khanoth",
//		"Luqman Koreja",
//		"Makhdoom Joon Landhyoon",
//		"Makhdoom Habibullah ji bani",
//		"Mano Machi",
//		"Qamar Sanai Boring",
//		"Qadoo koreja",
//		"Sain Bux Machi",
//		"Sukhpur",
//		"Sukhiyo Meerjat",
//		"Shafi Muhammad Daheri",
//		"Wahyoon Mahar",
//		"Wadero Lalan Machi",
//		"Wadero Yateem Machi",
//		"Wasoo machi",
//		"Waryo Matiwal" };
//		public static readonly string[] Villages_OldSaeedabad = { "Ali Nawaz Khoso-Loop Band",
//		"Allah Bux Khoso",
//		"Bilawal Khoso",
//		"Darya Khan Khoso",
//		"Gaji Bux Khoso",
//		"Gulab Goth",
//		"Ghazi Khan Khoso",
//		"Haji Hubo",
//		"Haji Mian Bux Khoso",
//		"Ibraheem Khoso",
//		"Juryo Gahoti",
//		"Kameja",
//		"Khad Wara Hajana",
//		"Kamejo-Khamiso Shaikh",
//		"Misri Khoso",
//		"Mangrio Chachar",
//		"Mahmood Hingora",
//		"Nawab Khoso",
//		"Nehal Khan Zardari",
//		"Old Saeedabad",
//		"Otaq Iqbal Shah-Jawed Pump",
//		"Otaq Pir Fazal Haq Shah",
//		"Otaq Bachal Shah",
//		"Otaq Mutoo Shah",
//		"Otaq moj Ali Shah-Suleman Sobcho",
//		"Pir Bux Khoso",
//		"Shah Muhammd Gahoti",
//		"Soomar Machi",
//		"Wanjheri Shareef-Otaq Ishfaq Shah",
//		"Ward 5 saeedabad",
//		"Yaro Khoso" };
//		public static readonly string[] Villages_RamzanUnar = { "Achar Hajano",
//"Agro Rahu",
//"Allah Warayo Rahu",
//"Allan Rahu",
//"Daim Rahu",
//"Darya Khan Hajano",
//"Jurio Hajano",
//"Khamiso Rahu",
//"Lutuf Rahu",
//"Paryo Rahu",
//"Pir Bux Kaka",
//"Ali Murad Birohi",
//"Dost Ali Zardari",
//"Ganwar Khan Zardari",
//"Ghulam Mustafa Magsi",
//"Governer Zardari",
//"Imdad zardari",
//"Khushal Zardari",
//"Kot Makhdoom Muhsin",
//"Kot Makhdoom Shahnawaz",
//"Mehboob Ali Zardari",
//"Pathan Zardari",
//"Sain Bux Magsi",
//"Abdul latif unar",
//"Ali Abad",
//"Ali Muhammad Brohi",
//"Ali Murad Gopang",
//"Ali Murad Talpur",
//"Allah Obhayo Unar",
//"Ghulam Muhammad Brohi",
//"Haji Zareen Brohi",
//"Jalal Chandio",
//"Jamal Brohi",
//"Kareem Bux Chandio",
//"Khamiso Brohi",
//"Mehmood Chandio",
//"Mitho Unar",
//"Muhammad Ayoob Unar",
//"Muhammad Juman Unar",
//"Ramzan Unar",
//"Musafir Brohi",
//"Nabi Bux Chandio",
//"Raes Porho Khan zardari",
//"Shokat Ali Unar",
//"Achi Masjid Rahu",
//"Arab Khan Jamali",
//"Arbab Padae",
//"Arz Muhammad Jamali",
//"Faiz Muhammad Jamali",
//"Gaji Rahu",
//"Haji Usman Rahu",
//"Hakeem Jamali",
//"Hussain Bux Jamali",
//"Kabool Rahu",
//"Khalifo Darya Khan Rahu",
//"Lakho Sand",
//"Loung Unar",
//"Mir Hassan Jamali",
//"Qadir Bux Jamali",
//"Qasim Unar",
//"Sajjan Faqeer Rahu",
//"Shafi Rahu",
//"Sijawal Rahu",
//"Majeedabad",
//"Khan Muhammad Ujan",
//"Wazeer Khan Zardari",
//"Ismail Unar",
//"Ghulam Qadir Jamali",
//"Wali Muhammad Brohi",
//"Muhammad Mosa",
//"Jan Muhammad Brohi",
//"Lal Bux Brohi",
//"Hashim Unar",
//"Umar Brohi" };
//		public static readonly string[] Villages_ShahmirRahu = { "Bago Rind",
//"Chakar Chandio",
//"Golho Hajano",
//"Hot Siyal",
//"Jumoo Hajano",
//"Khair Muhammad Magsi",
//"Kirar Jamali",
//"Kot Ali murad rahu",
//"Kot haji lal Punjabi",
//"Kot Javed Rahu",
//"Kot Nazeer Rahu",
//"Kot Sain Ismail Shah",
//"Maharabad",
//"Manzoorabad",
//"Masaoodabad",
//"Meer Muhammad Detho",
//"Mohan Kolhi",
//"Mushtaqabad",
//"Punhoo Rind",
//"Qadir Bux Detho",
//"Qaiser Detho",
//"Saeed Rahu",
//"Sher Muhammad Magsi",
//"Usman Machi",
//"Abdul Kareem Khaskheli",
//"Ahmed khan Rahu",
//"Amin Chandio",
//"Ayoub Rahu",
//"Balo Buriro",
//"Dano Hajano",
//"Dhib wara kolhi",
//"Din Muhammad rahu",
//"Dodo khan zardari",
//"Faiz Muhammad rahojo",
//"Faiz Rasool Rahu",
//"Ghulam Ali Jamali",
//"Haji Peer Bux Rahu",
//"Haji Waris Rahu Bagh",
//"Jumoo Hajanoo",
//"Kamal Khoso",
//"Kehar Jamali",
//"Khuda bux Malah",
//"Kot Haji Ali Nawaz",
//"Kot Umar Rahu",
//"Mitho Khan Hot",
//"Nawaz Rahu",
//"Roro Khokhar",
//"Shahmir Rahu",
//"Suleman Rahu",
//"Wali Muhammad Rahu",
//"Ali Khan Machi",
//"Arbab Mallah",
//"Jaimal Kolhi",
//"Jamal Chang",
//"Kod Bhanojo",
//"Matal Pasayo",
//"Meer Bhanojo",
//"Mola Bux Keeria",
//"Panjmoro",
//"Punho Jam Jamali",
//"Wali Muhammad Domki",
//"Sirachon Kaka",
//"Haji Idress Rahu",
//"Muhammad Saleh Keerio" };
//		public static readonly string[] Villages_Sikandarabad = { "Aalam Jamali",
//"Ali Muhammad kaka bagh",
//"Bakhar Jamali",
//"Baxshoo Jamali",
//"Karo Kaka",
//"Meer Khan Jamali",
//"Qadir Bux Jamali",
//"Sher Khan Jamali",
//"Aitbar Talpur",
//"Arbab Khan Jamali",
//"Bago Jamali",
//"Baloch Khan Jamali",
//"Gul Muhammad Brohi",
//"Haji Sohrab Jamali",
//"Imam Bux Jamali",
//"Mengal Brohi",
//"Nabi Bux Khaskheli",
//"Tharo Khan Jamali",
//"Abdul Aziz Colony",
//"Ali Khan Jamali",
//"Ali murad Jamali",
//"Dhingano Jamali",
//"Faqeer Muhammad Khaskheli",
//"Ghulam Hussain Khaskheli",
//"Ghulam Muhammad Khaskheli",
//"Haji Aalam Khaskheli",
//"Haji Essa Khaskheli",
//"Haji Rafi u din Jamali",
//"Jan Muhammad Jamali",
//"Madarsa manzoorabad",
//"Punhoo Jamali",
//"Shahdad Jamali",
//"Nazeer Hussain Jamali",
//"Wadi Kandiaro",
//"Bakhari",
//"Mola Bux Jamali" };
//		public static readonly string[] Villages_ZairPeer = { "Bachal kaka",
//"Boring Dadan Shah",
//"Essa Hanjano",
//"Goolo Jakhro",
//"Gul Muhammad Khoso",
//"Mahio Pir",
//"Mahrum Hajano",
//"Mevo Chachar",
//"Nawab Machi",
//"Pariyo Behan",
//"Siddique Rind",
//"Baig Shah",
//"Hyder Solangi",
//"Mahio Pir",
//"Awal Chachar",
//"Bakho Khokhar",
//"Dhani Bux Lashari",
//"Mullan Abass Keerio",
//"Punhoon unar",
//"Syed Ali Muhammad Shah",
//"Umaid Ali Lakho",
//"Essa Sand",
//"Ghulam Muhammad Bagrani",
//"Haji Imam Bux Zardari",
//"Haji Rozi Domki",
//"Khuda Bux Dal",
//"Meer Khan Malano",
//"Moula Bux Zardari",
//"Muhammad Ali Dal",
//"Nabi Bux jalalani",
//"Pathan Sand",
//"Rais Rajab Zardari",
//"Bachal Unar",
//"Kot Ghulam Muhammad Shah",
//"Kot Syed Ahmed Shah",
//"Lala Israr",
//"Umaid Ali Rind",
//"Zair peer",
//"Khan Muhammad sand",
//"Misri Bheel",
//"Chitori",
//"Bachal Kaka	",
//"Lakhmeer Zardari" };
    }
}
